// Copyright (c) 2022 Alibaba Group Holding Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: networking/v1/mcp_bridge.proto

// $schema: higress.networking.v1.McpBridge
// $title: McpBridge
// $description: Configuration affecting service discovery from multi registries
// $mode: none

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// <!-- crd generation tags
// +cue-gen:McpBridge:groupName:networking.higress.io
// +cue-gen:McpBridge:version:v1
// +cue-gen:McpBridge:storageVersion
// +cue-gen:McpBridge:annotations:helm.sh/resource-policy=keep
// +cue-gen:McpBridge:subresource:status
// +cue-gen:McpBridge:scope:Namespaced
// +cue-gen:McpBridge:resource:categories=higress-io,plural=mcpbridges
// +cue-gen:McpBridge:preserveUnknownFields:false
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=networking.higress.io/v1
// +genclient
// +k8s:deepcopy-gen=true
// -->
type McpBridge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registries    []*RegistryConfig      `protobuf:"bytes,1,rep,name=registries,proto3" json:"registries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpBridge) Reset() {
	*x = McpBridge{}
	mi := &file_networking_v1_mcp_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpBridge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpBridge) ProtoMessage() {}

func (x *McpBridge) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_mcp_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpBridge.ProtoReflect.Descriptor instead.
func (*McpBridge) Descriptor() ([]byte, []int) {
	return file_networking_v1_mcp_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *McpBridge) GetRegistries() []*RegistryConfig {
	if x != nil {
		return x.Registries
	}
	return nil
}

type RegistryConfig struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Type                   string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Domain                 string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Port                   uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	NacosAddressServer     string                 `protobuf:"bytes,5,opt,name=nacosAddressServer,proto3" json:"nacosAddressServer,omitempty"`
	NacosAccessKey         string                 `protobuf:"bytes,6,opt,name=nacosAccessKey,proto3" json:"nacosAccessKey,omitempty"`
	NacosSecretKey         string                 `protobuf:"bytes,7,opt,name=nacosSecretKey,proto3" json:"nacosSecretKey,omitempty"`
	NacosNamespaceId       string                 `protobuf:"bytes,8,opt,name=nacosNamespaceId,proto3" json:"nacosNamespaceId,omitempty"`
	NacosNamespace         string                 `protobuf:"bytes,9,opt,name=nacosNamespace,proto3" json:"nacosNamespace,omitempty"`
	NacosGroups            []string               `protobuf:"bytes,10,rep,name=nacosGroups,proto3" json:"nacosGroups,omitempty"`
	NacosRefreshInterval   int64                  `protobuf:"varint,11,opt,name=nacosRefreshInterval,proto3" json:"nacosRefreshInterval,omitempty"`
	ConsulNamespace        string                 `protobuf:"bytes,12,opt,name=consulNamespace,proto3" json:"consulNamespace,omitempty"`
	ZkServicesPath         []string               `protobuf:"bytes,13,rep,name=zkServicesPath,proto3" json:"zkServicesPath,omitempty"`
	ConsulDatacenter       string                 `protobuf:"bytes,14,opt,name=consulDatacenter,proto3" json:"consulDatacenter,omitempty"`
	ConsulServiceTag       string                 `protobuf:"bytes,15,opt,name=consulServiceTag,proto3" json:"consulServiceTag,omitempty"`
	ConsulRefreshInterval  int64                  `protobuf:"varint,16,opt,name=consulRefreshInterval,proto3" json:"consulRefreshInterval,omitempty"`
	AuthSecretName         string                 `protobuf:"bytes,17,opt,name=authSecretName,proto3" json:"authSecretName,omitempty"`
	Protocol               string                 `protobuf:"bytes,18,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Sni                    string                 `protobuf:"bytes,19,opt,name=sni,proto3" json:"sni,omitempty"`
	McpServerExportDomains []string               `protobuf:"bytes,20,rep,name=mcpServerExportDomains,proto3" json:"mcpServerExportDomains,omitempty"`
	McpServerBaseUrl       string                 `protobuf:"bytes,21,opt,name=mcpServerBaseUrl,proto3" json:"mcpServerBaseUrl,omitempty"`
	EnableMCPServer        *wrapperspb.BoolValue  `protobuf:"bytes,22,opt,name=enableMCPServer,proto3" json:"enableMCPServer,omitempty"`
	EnableScopeMcpServers  *wrapperspb.BoolValue  `protobuf:"bytes,23,opt,name=enableScopeMcpServers,proto3" json:"enableScopeMcpServers,omitempty"`
	AllowMcpServers        []string               `protobuf:"bytes,24,rep,name=allowMcpServers,proto3" json:"allowMcpServers,omitempty"`
	Metadata               map[string]*InnerMap   `protobuf:"bytes,25,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Vport                  *RegistryConfig_VPort  `protobuf:"bytes,26,opt,name=vport,proto3" json:"vport,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegistryConfig) Reset() {
	*x = RegistryConfig{}
	mi := &file_networking_v1_mcp_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryConfig) ProtoMessage() {}

func (x *RegistryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_mcp_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryConfig.ProtoReflect.Descriptor instead.
func (*RegistryConfig) Descriptor() ([]byte, []int) {
	return file_networking_v1_mcp_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *RegistryConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RegistryConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegistryConfig) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RegistryConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegistryConfig) GetNacosAddressServer() string {
	if x != nil {
		return x.NacosAddressServer
	}
	return ""
}

func (x *RegistryConfig) GetNacosAccessKey() string {
	if x != nil {
		return x.NacosAccessKey
	}
	return ""
}

func (x *RegistryConfig) GetNacosSecretKey() string {
	if x != nil {
		return x.NacosSecretKey
	}
	return ""
}

func (x *RegistryConfig) GetNacosNamespaceId() string {
	if x != nil {
		return x.NacosNamespaceId
	}
	return ""
}

func (x *RegistryConfig) GetNacosNamespace() string {
	if x != nil {
		return x.NacosNamespace
	}
	return ""
}

func (x *RegistryConfig) GetNacosGroups() []string {
	if x != nil {
		return x.NacosGroups
	}
	return nil
}

func (x *RegistryConfig) GetNacosRefreshInterval() int64 {
	if x != nil {
		return x.NacosRefreshInterval
	}
	return 0
}

func (x *RegistryConfig) GetConsulNamespace() string {
	if x != nil {
		return x.ConsulNamespace
	}
	return ""
}

func (x *RegistryConfig) GetZkServicesPath() []string {
	if x != nil {
		return x.ZkServicesPath
	}
	return nil
}

func (x *RegistryConfig) GetConsulDatacenter() string {
	if x != nil {
		return x.ConsulDatacenter
	}
	return ""
}

func (x *RegistryConfig) GetConsulServiceTag() string {
	if x != nil {
		return x.ConsulServiceTag
	}
	return ""
}

func (x *RegistryConfig) GetConsulRefreshInterval() int64 {
	if x != nil {
		return x.ConsulRefreshInterval
	}
	return 0
}

func (x *RegistryConfig) GetAuthSecretName() string {
	if x != nil {
		return x.AuthSecretName
	}
	return ""
}

func (x *RegistryConfig) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RegistryConfig) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *RegistryConfig) GetMcpServerExportDomains() []string {
	if x != nil {
		return x.McpServerExportDomains
	}
	return nil
}

func (x *RegistryConfig) GetMcpServerBaseUrl() string {
	if x != nil {
		return x.McpServerBaseUrl
	}
	return ""
}

func (x *RegistryConfig) GetEnableMCPServer() *wrapperspb.BoolValue {
	if x != nil {
		return x.EnableMCPServer
	}
	return nil
}

func (x *RegistryConfig) GetEnableScopeMcpServers() *wrapperspb.BoolValue {
	if x != nil {
		return x.EnableScopeMcpServers
	}
	return nil
}

func (x *RegistryConfig) GetAllowMcpServers() []string {
	if x != nil {
		return x.AllowMcpServers
	}
	return nil
}

func (x *RegistryConfig) GetMetadata() map[string]*InnerMap {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegistryConfig) GetVport() *RegistryConfig_VPort {
	if x != nil {
		return x.Vport
	}
	return nil
}

type InnerMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InnerMap      map[string]string      `protobuf:"bytes,1,rep,name=inner_map,json=innerMap,proto3" json:"inner_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerMap) Reset() {
	*x = InnerMap{}
	mi := &file_networking_v1_mcp_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerMap) ProtoMessage() {}

func (x *InnerMap) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_mcp_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerMap.ProtoReflect.Descriptor instead.
func (*InnerMap) Descriptor() ([]byte, []int) {
	return file_networking_v1_mcp_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *InnerMap) GetInnerMap() map[string]string {
	if x != nil {
		return x.InnerMap
	}
	return nil
}

type RegistryConfig_VPort struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Default       uint32                          `protobuf:"varint,1,opt,name=default,proto3" json:"default,omitempty"`
	Service       []*RegistryConfig_VPort_Service `protobuf:"bytes,2,rep,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryConfig_VPort) Reset() {
	*x = RegistryConfig_VPort{}
	mi := &file_networking_v1_mcp_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryConfig_VPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryConfig_VPort) ProtoMessage() {}

func (x *RegistryConfig_VPort) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_mcp_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryConfig_VPort.ProtoReflect.Descriptor instead.
func (*RegistryConfig_VPort) Descriptor() ([]byte, []int) {
	return file_networking_v1_mcp_bridge_proto_rawDescGZIP(), []int{1, 1}
}

func (x *RegistryConfig_VPort) GetDefault() uint32 {
	if x != nil {
		return x.Default
	}
	return 0
}

func (x *RegistryConfig_VPort) GetService() []*RegistryConfig_VPort_Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type RegistryConfig_VPort_Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         uint32                 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryConfig_VPort_Service) Reset() {
	*x = RegistryConfig_VPort_Service{}
	mi := &file_networking_v1_mcp_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryConfig_VPort_Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryConfig_VPort_Service) ProtoMessage() {}

func (x *RegistryConfig_VPort_Service) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1_mcp_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryConfig_VPort_Service.ProtoReflect.Descriptor instead.
func (*RegistryConfig_VPort_Service) Descriptor() ([]byte, []int) {
	return file_networking_v1_mcp_bridge_proto_rawDescGZIP(), []int{1, 1, 0}
}

func (x *RegistryConfig_VPort_Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegistryConfig_VPort_Service) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_networking_v1_mcp_bridge_proto protoreflect.FileDescriptor

const file_networking_v1_mcp_bridge_proto_rawDesc = "" +
	"\n" +
	"\x1enetworking/v1/mcp_bridge.proto\x12\x15higress.networking.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1cgoogle/protobuf/struct.proto\"R\n" +
	"\tMcpBridge\x12E\n" +
	"\n" +
	"registries\x18\x01 \x03(\v2%.higress.networking.v1.RegistryConfigR\n" +
	"registries\"\x93\v\n" +
	"\x0eRegistryConfig\x12\x17\n" +
	"\x04type\x18\x01 \x01(\tB\x03\xe0A\x02R\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\x06domain\x18\x03 \x01(\tB\x03\xe0A\x02R\x06domain\x12\x17\n" +
	"\x04port\x18\x04 \x01(\rB\x03\xe0A\x02R\x04port\x12.\n" +
	"\x12nacosAddressServer\x18\x05 \x01(\tR\x12nacosAddressServer\x12&\n" +
	"\x0enacosAccessKey\x18\x06 \x01(\tR\x0enacosAccessKey\x12&\n" +
	"\x0enacosSecretKey\x18\a \x01(\tR\x0enacosSecretKey\x12*\n" +
	"\x10nacosNamespaceId\x18\b \x01(\tR\x10nacosNamespaceId\x12&\n" +
	"\x0enacosNamespace\x18\t \x01(\tR\x0enacosNamespace\x12 \n" +
	"\vnacosGroups\x18\n" +
	" \x03(\tR\vnacosGroups\x122\n" +
	"\x14nacosRefreshInterval\x18\v \x01(\x03R\x14nacosRefreshInterval\x12(\n" +
	"\x0fconsulNamespace\x18\f \x01(\tR\x0fconsulNamespace\x12&\n" +
	"\x0ezkServicesPath\x18\r \x03(\tR\x0ezkServicesPath\x12*\n" +
	"\x10consulDatacenter\x18\x0e \x01(\tR\x10consulDatacenter\x12*\n" +
	"\x10consulServiceTag\x18\x0f \x01(\tR\x10consulServiceTag\x124\n" +
	"\x15consulRefreshInterval\x18\x10 \x01(\x03R\x15consulRefreshInterval\x12&\n" +
	"\x0eauthSecretName\x18\x11 \x01(\tR\x0eauthSecretName\x12\x1a\n" +
	"\bprotocol\x18\x12 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03sni\x18\x13 \x01(\tR\x03sni\x126\n" +
	"\x16mcpServerExportDomains\x18\x14 \x03(\tR\x16mcpServerExportDomains\x12*\n" +
	"\x10mcpServerBaseUrl\x18\x15 \x01(\tR\x10mcpServerBaseUrl\x12D\n" +
	"\x0fenableMCPServer\x18\x16 \x01(\v2\x1a.google.protobuf.BoolValueR\x0fenableMCPServer\x12P\n" +
	"\x15enableScopeMcpServers\x18\x17 \x01(\v2\x1a.google.protobuf.BoolValueR\x15enableScopeMcpServers\x12(\n" +
	"\x0fallowMcpServers\x18\x18 \x03(\tR\x0fallowMcpServers\x12O\n" +
	"\bmetadata\x18\x19 \x03(\v23.higress.networking.v1.RegistryConfig.MetadataEntryR\bmetadata\x12A\n" +
	"\x05vport\x18\x1a \x01(\v2+.higress.networking.v1.RegistryConfig.VPortR\x05vport\x1a\\\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.higress.networking.v1.InnerMapR\x05value:\x028\x01\x1a\xa5\x01\n" +
	"\x05VPort\x12\x18\n" +
	"\adefault\x18\x01 \x01(\rR\adefault\x12M\n" +
	"\aservice\x18\x02 \x03(\v23.higress.networking.v1.RegistryConfig.VPort.ServiceR\aservice\x1a3\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value\"\x93\x01\n" +
	"\bInnerMap\x12J\n" +
	"\tinner_map\x18\x01 \x03(\v2-.higress.networking.v1.InnerMap.InnerMapEntryR\binnerMap\x1a;\n" +
	"\rInnerMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B.Z,github.com/alibaba/higress/api/networking/v1b\x06proto3"

var (
	file_networking_v1_mcp_bridge_proto_rawDescOnce sync.Once
	file_networking_v1_mcp_bridge_proto_rawDescData []byte
)

func file_networking_v1_mcp_bridge_proto_rawDescGZIP() []byte {
	file_networking_v1_mcp_bridge_proto_rawDescOnce.Do(func() {
		file_networking_v1_mcp_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_networking_v1_mcp_bridge_proto_rawDesc), len(file_networking_v1_mcp_bridge_proto_rawDesc)))
	})
	return file_networking_v1_mcp_bridge_proto_rawDescData
}

var file_networking_v1_mcp_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_networking_v1_mcp_bridge_proto_goTypes = []any{
	(*McpBridge)(nil),                    // 0: higress.networking.v1.McpBridge
	(*RegistryConfig)(nil),               // 1: higress.networking.v1.RegistryConfig
	(*InnerMap)(nil),                     // 2: higress.networking.v1.InnerMap
	nil,                                  // 3: higress.networking.v1.RegistryConfig.MetadataEntry
	(*RegistryConfig_VPort)(nil),         // 4: higress.networking.v1.RegistryConfig.VPort
	(*RegistryConfig_VPort_Service)(nil), // 5: higress.networking.v1.RegistryConfig.VPort.Service
	nil,                                  // 6: higress.networking.v1.InnerMap.InnerMapEntry
	(*wrapperspb.BoolValue)(nil),         // 7: google.protobuf.BoolValue
}
var file_networking_v1_mcp_bridge_proto_depIdxs = []int32{
	1, // 0: higress.networking.v1.McpBridge.registries:type_name -> higress.networking.v1.RegistryConfig
	7, // 1: higress.networking.v1.RegistryConfig.enableMCPServer:type_name -> google.protobuf.BoolValue
	7, // 2: higress.networking.v1.RegistryConfig.enableScopeMcpServers:type_name -> google.protobuf.BoolValue
	3, // 3: higress.networking.v1.RegistryConfig.metadata:type_name -> higress.networking.v1.RegistryConfig.MetadataEntry
	4, // 4: higress.networking.v1.RegistryConfig.vport:type_name -> higress.networking.v1.RegistryConfig.VPort
	6, // 5: higress.networking.v1.InnerMap.inner_map:type_name -> higress.networking.v1.InnerMap.InnerMapEntry
	2, // 6: higress.networking.v1.RegistryConfig.MetadataEntry.value:type_name -> higress.networking.v1.InnerMap
	5, // 7: higress.networking.v1.RegistryConfig.VPort.service:type_name -> higress.networking.v1.RegistryConfig.VPort.Service
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_networking_v1_mcp_bridge_proto_init() }
func file_networking_v1_mcp_bridge_proto_init() {
	if File_networking_v1_mcp_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_networking_v1_mcp_bridge_proto_rawDesc), len(file_networking_v1_mcp_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_networking_v1_mcp_bridge_proto_goTypes,
		DependencyIndexes: file_networking_v1_mcp_bridge_proto_depIdxs,
		MessageInfos:      file_networking_v1_mcp_bridge_proto_msgTypes,
	}.Build()
	File_networking_v1_mcp_bridge_proto = out.File
	file_networking_v1_mcp_bridge_proto_goTypes = nil
	file_networking_v1_mcp_bridge_proto_depIdxs = nil
}
